### PR TITLE
Add exotic higgs decays mc analysis code and scripts

### PR DESCRIPTION
**Pull request by mvoorde**
Code and scripts related to do analysis of the exotic higgs decays at MC level

### CODE REVIEW

**Comment by jalimena** [comment]
This PR also looks good, except I'm wondering if we can move the code within ExoticHiggsDecays_analysis_code/ to somewhere else in the existing FCCAnalyses structure, rather than making a whole new subdirectory just for this analysis. Maybe the relevant parts can go in here:
https://github.com/FCC-LLP/FCCAnalyses/blob/master/analyzers/dataframe/src/myUtils.cc
? You could also ask Clement's opinion about where to add this analysis code within the existing structure.

**Comment by mvoorde** [comment]
Agree! I will move the code to "myUtils" and do the corresponding changes in the MC_analysis_stage1 that is needed. Should I update this PR with the changes then? Or close it and open a new one?

**Comment by jalimena** [comment]
i think you can make the changes still right here. just push your changes to add_ExoticHiggsDecays_MC_analysis, and they will appear automatically here in the PR

**Comment by jalimena** [comment]
ok! i think this PR is good to go. @mvoorde , can you confirm from your side it is done? if so, i will merge it

**Comment by mvoorde** [comment]
Yes, it's good to go!

**Pull request merged**
